version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: task-board-server
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_YXPMZvStau26@ep-restless-butterfly-ad6b6hxr-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      NODE_ENV: development
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
